part1

1st,2nd,3rd question

In [35]:
import numpy as np
list1=[1,2,3]
n1=np.array(list1)
print("list1",list1)
print("n1",n1)
print("type=",type(n1))
print("type=",type(list1))

list1 [1, 2, 3]
n1 [1 2 3]
type= <class 'numpy.ndarray'>
type= <class 'list'>


# 4th question


In [36]:

import numpy as np
arr1=(11,22,33,44)
arr2=(11,22,33,44)
mul=np.multiply(arr1,arr2)
print(mul)
div=np.divide(arr1,arr2)
print(div)
pow=np.power(arr1,arr2)
print(pow)

[ 121  484 1089 1936]
[1. 1. 1. 1.]
[        285311670611  4981753131911086080 -4053175462519618527
                    0]


5th question


In [ ]:
data1 = np.array([2, 4, 6, 8, 10])
data2 =np.array( [1, 2, 3, 4, 5])
print("addition of two array:",data1+data2)

6th question


In [25]:
print(np.sin(list1))
print(np.log(list1))
print(np.log2(list1))
print(np.exp(list1))


[ 0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111]
[0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
[1.         2.         2.5849625  3.         3.32192809]
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
